export const LEAD_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  UNQUALIFIED: 'UNQUALIFIED',
  QUOTED: 'QUOTED',
  WON: 'WON',
  LOST: 'LOST',
} as const

export const TIMELINE = {
  ASAP: 'ASAP',
  THIS_WEEK: 'THIS_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  FLEXIBLE: 'FLEXIBLE',
} as const
  